#!/usr/bin/env python3
"""Compile rules/*.md into every agent surface.

    rules/*.md  (source of truth)
        ├─ tier 0  ─→ CLAUDE.md · AGENTS.md · .github/copilot-instructions.md
        ├─ applyTo ─→ .github/instructions/<id>.instructions.md
        └─ skills  ─→ referenced by path from .claude/skills/*/SKILL.md

Generated regions are fenced with <!-- GENERATED:<name>:start|end --> so hand-written
prose in the same file survives regeneration. Files under .github/instructions/ are
generated in full.

Usage:
    python tools/sync_rules.py            # write
    python tools/sync_rules.py --check    # exit 1 if anything is stale (CI gate)

No third-party dependencies: this must run in any repo that adopts the layout.
"""

from __future__ import annotations

import argparse
import fnmatch
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = ROOT / "rules"
SKILLS_DIR = ROOT / ".claude" / "skills"
INSTRUCTIONS_DIR = ROOT / ".github" / "instructions"

FM_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", re.DOTALL)
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$", re.MULTILINE)

BANNER = (
    "<!-- Generated by tools/sync_rules.py from rules/*.md. Do not edit by hand: "
    "changes are overwritten on the next sync. Edit the rule pack instead. -->"
)


# --------------------------------------------------------------------------- parsing


def parse_scalar(raw: str) -> object:
    """Parse the small YAML subset the frontmatter actually uses."""
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [item.strip().strip("\"'") for item in inner.split(",") if item.strip()]
    if raw.startswith(('"', "'")) and raw.endswith(('"', "'")) and len(raw) >= 2:
        return raw[1:-1]
    if raw.isdigit():
        return int(raw)
    return raw


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse frontmatter, honouring YAML's indented continuation lines.

    A wrapped value is one value:

        description: Run a multi-pass review of a pull request
          using parallel specialist agents.

    Reading line-by-line and requiring a colon silently truncates that to the first
    line, which under-reports skill descriptions in the token budget and would mangle
    any wrapped `applyTo` glob.
    """
    m = FM_RE.match(text)
    if not m:
        return {}, text

    meta: dict[str, object] = {}
    key: str | None = None
    buf: list[str] = []

    def flush() -> None:
        if key is not None:
            meta[key] = parse_scalar(" ".join(buf))

    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[:1].isspace() and key is not None:
            buf.append(line.strip())
            continue
        if ":" not in line:
            continue
        flush()
        raw_key, _, value = line.partition(":")
        key, buf = raw_key.strip(), [value.strip()]
    flush()
    return meta, m.group(2)


def split_globs(raw: str) -> list[str]:
    """Split a comma-separated glob list without breaking brace expansions.

    `**/*.{c,h,cpp}` contains commas that belong to the brace group. Splitting on every
    comma yields `**/*.{c`, `h`, `cpp}`, which rejoins as `**/*.{c, h, cpp}` — a glob
    whose alternatives now carry leading spaces, so it matches nothing and the rules
    silently never load.
    """
    out: list[str] = []
    buf: list[str] = []
    depth = 0
    for ch in raw:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
        elif ch == "," and depth == 0:
            out.append("".join(buf).strip())
            buf = []
            continue
        buf.append(ch)
    out.append("".join(buf).strip())
    return [g for g in out if g]


# ------------------------------------------------------------------------- profiles


PROFILES_MD = RULES_DIR / "PROFILES.md"
PROFILE_SECTION_RE = re.compile(r"^##\s+([\w-]+)\s*$", re.M)
PROFILE_KEY_RE = re.compile(
    r"^\s*(packs|skills):\s*(.+?)(?=^\s*(?:packs|skills):|\Z)", re.M | re.S
)
ALWAYS_PACKS = {"core"}       # the contract is never optional
ALWAYS_SKILLS = {"rulesmith"}  # without it the repo cannot edit itself


def load_profiles() -> tuple[str, dict[str, dict[str, list[str]]]]:
    """Parse rules/PROFILES.md into (active name, {profile: {packs, skills}}).

    Lives here rather than in profile.py because the compiler needs the pack filter,
    and a second parser would drift from this one.
    """
    if not PROFILES_MD.exists():
        return "full", {"full": {"packs": ["*"], "skills": ["*"]}}
    meta, body = parse_frontmatter(PROFILES_MD.read_text(encoding="utf-8"))
    active = str(meta.get("active", "full"))

    profiles: dict[str, dict[str, list[str]]] = {}
    matches = list(PROFILE_SECTION_RE.finditer(body))
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        block = body[m.end() : end].replace("```", " ")
        entry: dict[str, list[str]] = {"packs": [], "skills": []}
        for km in PROFILE_KEY_RE.finditer(block):
            entry[km.group(1)] = [
                v.strip() for v in km.group(2).split(",") if v.strip()
            ]
        if entry["packs"] or entry["skills"]:
            profiles[m.group(1)] = entry
    return active, profiles


def expand(patterns: list[str], universe: set[str], always: set[str]) -> set[str]:
    """Resolve a list of ids and globs against the installed set."""
    out: set[str] = set(always & universe)
    for pat in patterns:
        if any(ch in pat for ch in "*?["):
            out |= {u for u in universe if fnmatch.fnmatch(u, pat)}
        elif pat in universe:
            out.add(pat)
    return out


def active_pack_ids(packs: list[Pack]) -> tuple[str, set[str]]:
    """(profile name, pack ids the profile enables). Unknown profile ⇒ everything."""
    active, profiles = load_profiles()
    universe = {p.id for p in packs}
    if active not in profiles:
        return active, universe
    return active, expand(profiles[active]["packs"], universe, ALWAYS_PACKS)


@dataclass
class Pack:
    id: str
    title: str
    tier: int
    apply_to: str
    skills: list[str]
    owner: str
    body: str
    path: Path
    sections: dict[str, str] = field(default_factory=dict)

    @property
    def globs(self) -> list[str]:
        return split_globs(self.apply_to)


def load_packs() -> list[Pack]:
    packs: list[Pack] = []
    for path in sorted(RULES_DIR.glob("*.md")):
        if path.stem.isupper():  # INDEX, BIBLIOGRAPHY — navigation, not rules
            continue
        meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not meta.get("id"):
            print(f"  ! {path.name}: missing frontmatter `id` — skipped", file=sys.stderr)
            continue
        if meta["id"] != path.stem:
            print(
                f"  ! {path.name}: id '{meta['id']}' does not match filename — skipped",
                file=sys.stderr,
            )
            continue
        skills = meta.get("skills") or []
        # `or 2` would be wrong here: tier 0 is falsy and would silently become tier 2,
        # dropping the contract from every always-on surface.
        raw_tier = meta.get("tier", 2)
        tier = int(raw_tier) if raw_tier not in (None, "") else 2
        packs.append(
            Pack(
                id=str(meta["id"]),
                title=str(meta.get("title", meta["id"])),
                tier=tier,
                apply_to=str(meta.get("applyTo", "") or ""),
                skills=[str(s) for s in (skills if isinstance(skills, list) else [skills])],
                owner=str(meta.get("owner", "unassigned")),
                body=body.strip(),
                path=path,
                sections=split_sections(body),
            )
        )
    return packs


def split_sections(body: str) -> dict[str, str]:
    out: dict[str, str] = {}
    matches = list(SECTION_RE.finditer(body))
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
        out[m.group(1).strip()] = body[m.end() : end].strip()
    return out


def load_skills() -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    if not SKILLS_DIR.is_dir():
        return out
    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        meta, _ = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        name = str(meta.get("name", skill_md.parent.name))
        desc = " ".join(str(meta.get("description", "")).split())
        out.append((name, desc))
    return out


# ------------------------------------------------------------------------ rendering


RATIONALE_RE = re.compile(r"^\s*\*(Why|Check):\*", re.IGNORECASE)
NEW_ITEM_RE = re.compile(r"^\s*(\d+\.|[-*+])\s")


def strip_rationale(content: str) -> str:
    """Keep the imperative; drop *Why:* / *Check:* lines.

    This is progressive disclosure applied to tier 0 itself. The always-on surface
    carries the instruction; the reasoning and the verification command stay in the
    pack, which the agent reads only when it needs to justify or check a rule. It is
    the difference between a ~600-token contract and a ~1,300-token one, paid on
    every turn of every session.
    """
    kept: list[str] = []
    skipping = False
    for ln in content.splitlines():
        if RATIONALE_RE.match(ln):
            skipping = True  # drop this line and its wrapped continuation
            continue
        if skipping:
            stripped = ln.strip()
            is_continuation = (
                stripped
                and ln[:1].isspace()
                and not NEW_ITEM_RE.match(ln)
                and not ln.lstrip().startswith("#")
            )
            if is_continuation:
                continue
            skipping = False
        kept.append(ln.rstrip())

    # Collapse blank runs left behind by the removals.
    out: list[str] = []
    for ln in kept:
        if not ln.strip() and out and not out[-1].strip():
            continue
        out.append(ln)
    return "\n".join(out).strip()


def render_tier0(packs: list[Pack]) -> str:
    lines: list[str] = []
    tier0 = [p for p in packs if p.tier == 0]
    for pack in tier0:
        for section in ("Non-negotiable", "Prefer", "Avoid"):
            content = pack.sections.get(section)
            if content:
                lines.append(f"### {section}\n")
                lines.append(strip_rationale(content))
                lines.append("")
    if tier0:
        ids = " · ".join(f"`rules/{p.id}.md`" for p in tier0)
        lines.append(f"Rationale and verification commands for each rule: {ids}")
    return "\n".join(lines).strip()


ENGINEERING = {
    "context",
    "model-routing",
    "planning",
    "codebase-work",
    "code-review",
    "system-design",
    "scheduling",
    "performance",
    "memory-safety",
    "memory-management",
    "computer-architecture",
    "security",
    "appsec",
    "security-compliance",
    "testing",
    "local-dev",
    "ux-design",
    "agents",
    "agent-integration",
    "concurrency",
    "observability",
}


def pack_group(p: Pack) -> str:
    if p.tier == 0:
        return "Contract"
    if p.id.startswith("lang-"):
        return "Languages"
    if p.id in ENGINEERING:
        return "Engineering"
    return "Domain"


def render_pack_list(packs: list[Pack]) -> str:
    """Counts and a pointer — deliberately not an enumeration.

    This block lands in an always-on surface, so enumerating pack ids costs ~8 tokens
    per pack on *every turn* and grows without bound as packs are added. The routing
    table itself (rules/INDEX.md) is one on-demand read. Over a 40-turn session that is
    ~750 tokens once instead of ~13,000.
    """
    groups: dict[str, int] = {}
    for p in packs:
        if p.tier == 0:
            continue  # the contract is rendered inline above this block
        groups[pack_group(p)] = groups.get(pack_group(p), 0) + 1
    order = ["Engineering", "Languages", "Domain"]
    counts = " · ".join(f"{groups[g]} {g.lower()}" for g in order if g in groups)
    return (
        f"`rules/` holds {sum(groups.values())} packs: {counts}.\n\n"
        f"**Read `rules/INDEX.md` to find the one that matches your task** — it maps "
        f"pack to subject in one table. Load only that pack. Each pack may point to a "
        f"`rules/references/<id>.md` appendix; load that only when implementing."
    )


def render_prompt_list() -> str:
    prompts = sorted((ROOT / ".github" / "prompts").glob("*.prompt.md"))
    modes = sorted((ROOT / ".github" / "chatmodes").glob("*.chatmode.md"))
    lines = []
    if prompts:
        names = " · ".join(f"`/{p.name.removesuffix('.prompt.md')}`" for p in prompts)
        lines.append(f"- Prompt files: {names}")
    if modes:
        names = " · ".join(f"`{m.name.removesuffix('.chatmode.md')}`" for m in modes)
        lines.append(f"- Chat modes: {names}")
    return "\n".join(lines)


def render_instruction_file(pack: Pack) -> str:
    globs = ", ".join(pack.globs)
    desc = f"{pack.title} — compiled from rules/{pack.id}.md"
    parts = [
        "---",
        f"applyTo: '{globs}'",
        f"description: '{desc}'",
        "---",
        "",
        BANNER,
        "",
        f"# {pack.title}",
        "",
        f"Source of truth: `rules/{pack.id}.md` (owner: {pack.owner}). "
        f"Cite rules as `{pack.id}#N`.",
        "",
        pack.body,
        "",
    ]
    return "\n".join(parts)


def render_copilot_root(packs: list[Pack]) -> str:
    """Always-on Copilot surface.

    Path-scoped packs are deliberately NOT listed: Copilot loads them automatically
    from .github/instructions/ when a matching file is in play, so naming them here
    would pay for the same routing twice on every request.
    """
    unscoped = [p for p in packs if p.tier != 0 and not p.globs]
    lines = [
        BANNER,
        "",
        "# Repository instructions",
        "",
        render_tier0(packs),
        "",
        "## Detail loads on demand",
        "",
        "- Language, domain, and infrastructure rules load automatically from "
        "`.github/instructions/` when you touch a matching file.",
    ]
    if unscoped:
        ids = " · ".join(f"`rules/{p.id}.md`" for p in unscoped)
        lines.append(f"- Not path-scopeable — read when relevant: {ids}")
    lines += ["- Full index with owners: `rules/INDEX.md`. Cite rules as `pack-id#n`."]
    prompts = render_prompt_list()
    if prompts:
        lines += ["", "## Reusable tasks", "", prompts]
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------- marker splice


def splice(text: str, name: str, payload: str, where: str) -> str:
    """Replace a marked region in place.

    Absent markers are a no-op, not an append: the file's author decides which
    generated blocks belong in it and where. Appending would quietly re-add a block
    someone deliberately removed.
    """
    start = f"<!-- GENERATED:{name}:start -->"
    end = f"<!-- GENERATED:{name}:end -->"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        print(f"  . {where}: no '{name}' marker — block not inserted", file=sys.stderr)
        return text
    return pattern.sub(lambda _: f"{start}\n{payload}\n{end}", text, count=1)


# --------------------------------------------------------------------------- driver


def write(path: Path, content: str, check: bool, stale: list[str]) -> None:
    content = content.rstrip() + "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    if check:
        stale.append(str(path.relative_to(ROOT)))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if output is stale")
    args = ap.parse_args()

    packs = load_packs()
    if not packs:
        print("No rule packs found in rules/", file=sys.stderr)
        return 1
    skills = load_skills()
    stale: list[str] = []

    # References must be reachable in both directions: a file nobody points at never
    # loads, and a pointer to a missing file sends the agent looking for nothing.
    refs_dir = RULES_DIR / "references"
    ref_problems = 0
    if refs_dir.is_dir():
        by_id = {p.id: p for p in packs}
        for ref in sorted(refs_dir.glob("*.md")):
            pack = by_id.get(ref.stem)
            if pack is None:
                print(f"  ! references/{ref.name}: no matching pack", file=sys.stderr)
                ref_problems += 1
            elif f"references/{ref.stem}.md" not in pack.body:
                print(
                    f"  ! rules/{ref.stem}.md does not point at its reference file",
                    file=sys.stderr,
                )
                ref_problems += 1
    for pack in packs:
        if f"references/{pack.id}.md" in pack.body and not (
            refs_dir / f"{pack.id}.md"
        ).exists():
            print(
                f"  ! rules/{pack.id}.md points at a missing reference file",
                file=sys.stderr,
            )
            ref_problems += 1

    tier0 = render_tier0(packs)
    pack_list = render_pack_list(packs)

    # 1. Marker-spliced surfaces (hand-written prose preserved).
    #    CLAUDE.md deliberately gets no skill block: Claude already loads every skill
    #    description natively as tier 1 (~1.1k tokens), so listing them here would pay
    #    for the same routing twice on every request.
    for rel, blocks in {
        "CLAUDE.md": {"tier0": tier0},
        "AGENTS.md": {"tier0": tier0, "packs": pack_list},
    }.items():
        path = ROOT / rel
        if not path.exists():
            print(f"  ! {rel} missing — skipped", file=sys.stderr)
            continue
        text = path.read_text(encoding="utf-8")
        for name, payload in blocks.items():
            text = splice(text, name, payload, rel)
        write(path, text, args.check, stale)

    # 2. Fully generated surfaces
    write(
        ROOT / ".github" / "copilot-instructions.md",
        render_copilot_root(packs),
        args.check,
        stale,
    )

    profile, enabled = active_pack_ids(packs)
    scoped = [p for p in packs if p.tier != 0 and p.globs and p.id in enabled]
    for pack in scoped:
        write(
            INSTRUCTIONS_DIR / f"{pack.id}.instructions.md",
            render_instruction_file(pack),
            args.check,
            stale,
        )

    # 3. Remove orphans
    if INSTRUCTIONS_DIR.is_dir():
        keep = {f"{p.id}.instructions.md" for p in scoped}
        for f in INSTRUCTIONS_DIR.glob("*.instructions.md"):
            if f.name not in keep:
                if args.check:
                    stale.append(f"{f.relative_to(ROOT)} (orphaned)")
                else:
                    f.unlink()
                    print(f"  removed {f.relative_to(ROOT)} (orphaned)")

    if args.check:
        if stale:
            print("Generated files are stale:", file=sys.stderr)
            for s in stale:
                print(f"  - {s}", file=sys.stderr)
            print("\nRun: python tools/sync_rules.py", file=sys.stderr)
            return 1
        if ref_problems:
            print(f"{ref_problems} reference linkage problem(s)", file=sys.stderr)
            return 1
        print(
            f"In sync [{profile}]: {len(enabled)}/{len(packs)} packs, {len(scoped)} scoped, "
            f"{len(list(refs_dir.glob('*.md'))) if refs_dir.is_dir() else 0} references, "
            f"{len(skills)} skills."
        )
        return 0

    print(
        f"\nSynced {len(packs)} packs "
        f"[{profile}] ({len(enabled)}/{len(packs)} enabled, {len(scoped)} scoped) "
        f"and {len(skills)} skills."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
